# on: [ pull_request ]

name: Test Coverage

jobs:

  coverage:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install
      run: |
        npm install
        npm install --no-save nyc codecov

    - run: npm run cover

    - name: Submit to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
