name: Test Coverage

on: [ push ]

jobs:

  coverage:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install
      run: |
        npm install
        npm install --no-save nyc codecov

    - run: NODE_ENV=cov npx nyc --reporter=lcovonly npm test

    - name: Submit to Coveralls
      if: success()
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
