name: publish

on:
  release:
    types: [ published ]
  push:
    branches:
      - master
    paths:
      - package.json

env:
  CI: true

jobs:
  publish:
    uses: haraka/.github/.github/workflows/publish.yml@master
    secrets: inherit
